version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: cybersecurity_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: cybersecurity_platform
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - cybersecurity_network

  app:
    build: .
    container_name: cybersecurity_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/cybersecurity_platform?authSource=admin
      JWT_SECRET: your-super-secure-jwt-secret-key-here-change-in-production
      SESSION_SECRET: your-session-secret-key-here-change-in-production
      ENCRYPTION_KEY: your-32-character-encryption-key-here-change-in-production
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - cybersecurity_network

  nginx:
    image: nginx:alpine
    container_name: cybersecurity_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - cybersecurity_network

volumes:
  mongodb_data:

networks:
  cybersecurity_network:
    driver: bridge